name: sqflite_ext
description: Useful utilities to augment sqflite.
version: 1.1.2
homepage: https://github.com/justinlettau/sqflite_ext

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  path: ^1.8.3
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
